### ISSUE TITLE
Crash on startup - signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf13031

### ISSUE THREAD

**Issue by mitchds** [ipfs-cluster/ipfs-cluster#1796]
```
/usr/bin/ipfs-cluster-service daemon 
2022-11-13T17:31:16.106+0400	INFO	service	ipfs-cluster-service/daemon.go:49	Initializing. For verbose output run with "-l debug". Please wait...
2022-11-13T17:31:16.126+0400	INFO	badger	badger@v1.6.2/logger.go:46	All 0 tables opened in 0s

2022-11-13T17:31:16.126+0400	INFO	badger	badger@v1.6.2/logger.go:46	Replaying file id: 0 at offset: 0

2022-11-13T17:31:16.126+0400	INFO	badger	badger@v1.6.2/logger.go:46	Replay took: 5.866µs

2022-11-13T17:31:16.127+0400	INFO	service	ipfs-cluster-service/daemon.go:267	Datastore backend: badger
2022-11-13T17:31:16.161+0400	INFO	cluster	ipfs-cluster@v1.0.4/cluster.go:137	IPFS Cluster v1.0.4 listening on:
        /ip4/10.0.0.10/tcp/9096/p2p/12D3KooWGtzjXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        /ip4/127.0.0.1/tcp/9096/p2p/12D3KooWGtzjjXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX


2022-11-13T17:31:16.831+0400	INFO	pinsvcapi	common/api.go:460	PINSVCAPI (HTTP): /ip4/127.0.0.1/tcp/9097
2022-11-13T17:31:16.831+0400	INFO	restapi	common/api.go:460	RESTAPI (HTTP): /ip4/127.0.0.1/tcp/9094
2022-11-13T17:31:16.831+0400	INFO	ipfsproxy	ipfsproxy/ipfsproxy.go:331	IPFS Proxy: /ip4/127.0.0.1/tcp/9095 -> /ip4/10.0.0.10/tcp/5001
2022-11-13T17:31:16.833+0400	INFO	crdt	go-ds-crdt@v0.3.9/set.go:122	Tombstones have bloomed: 0 tombs. Took: 170.972µs
2022-11-13T17:31:16.833+0400	INFO	crdt	go-ds-crdt@v0.3.9/crdt.go:296	crdt Datastore created. Number of heads: 0. Current max-height: 0. Dirty: false
2022-11-13T17:31:16.833+0400	INFO	crdt	crdt/consensus.go:319	'trust all' mode enabled. Any peer in the cluster can modify the pinset.
2022-11-13T17:31:16.834+0400	INFO	cluster	ipfs-cluster@v1.0.4/cluster.go:735	Cluster Peers (without including ourselves):
2022-11-13T17:31:16.834+0400	INFO	cluster	ipfs-cluster@v1.0.4/cluster.go:742	    - 12D3KooWNBCB6jXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
2022-11-13T17:31:16.834+0400	INFO	cluster	ipfs-cluster@v1.0.4/cluster.go:747	Waiting for IPFS to be ready...
2022-11-13T17:31:16.834+0400	INFO	crdt	go-ds-crdt@v0.3.9/crdt.go:505	store is marked clean. No need to repair
2022-11-13T17:31:16.836+0400	INFO	cluster	ipfs-cluster@v1.0.4/cluster.go:756	IPFS is ready. Peer ID: QmawbFWECFk6jXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
2022-11-13T17:31:16.836+0400	INFO	cluster	ipfs-cluster@v1.0.4/cluster.go:764	** IPFS Cluster is READY **
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf13031]

goroutine 754 [running]:
github.com/libp2p/go-libp2p/p2p/host/autorelay.(*relayFinder).findNodes(0xc000a2ea90, {0x1aaeb70?, 0xc004802e80})
	github.com/libp2p/go-libp2p@v0.22.0/p2p/host/autorelay/relay_finder.go:209 +0x51
github.com/libp2p/go-libp2p/p2p/host/autorelay.(*relayFinder).background.func2()
	github.com/libp2p/go-libp2p@v0.22.0/p2p/host/autorelay/relay_finder.go:112 +0x66
created by github.com/libp2p/go-libp2p/p2p/host/autorelay.(*relayFinder).background
	github.com/libp2p/go-libp2p@v0.22.0/p2p/host/autorelay/relay_finder.go:110 +0x192
  home ~  /usr/bin/ipfs-cluster-service --version
ipfs-cluster-service version 1.0.4
```

**Additional information:**
 - OS: Linux/Ubuntu
 - IPFS Cluster version: 1.0.4
 - Installation method: binary from github
**Describe the bug:**

Constantly crashing on startup. 100% reproducible. Am behind a NAT gateway, and port is getting punched in my router correctly.

**Comment by hsanjuan** [comment]
I can't reproduce it, but it is related to https://github.com/libp2p/go-libp2p/issues/1852 . I will send a fix asap.

**Comment by SmaugPool** [comment]
Hi, is there a work-around with v1.0.4 until a new version is released?

I setup a new cluster and it's constantly crashing.

**Comment by hsanjuan** [comment]
@SmaugPool you would need to pick #1797 . I'm still  not sure why it happens all the time for some people and not others.

**Comment by SmaugPool** [comment]
It happened when connections from remote cluster peers were not allowed in the firewall (but connections to remote peers were).
As soon as they were allowed, the issues disappeared. By the way it already happened in 1.0.3.
