### ISSUE TITLE
Pebble datastore deadlocked

### ISSUE THREAD

**Issue by Mayeu** [ipfs-cluster/ipfs-cluster#2009]
**Additional information:**
 - OS: Linux (NixOS, commit bf744fe90419885eefced41b3e5ae442d732712d)
 - IPFS Cluster version: 1.0.7
 - Installation method: from NixOS default repository ([nixpkgs](https://github.com/NixOS/nixpkgs/blob/6b43e4b0bc862d2e6a2ad18731ee93bcf899c93a/pkgs/applications/networking/ipfs-cluster/default.nix))

**Describe the bug:**

Hello,

We have an application that tracks all the CIDs we need to pin (around 14.5 million), this application is in charge of monitoring our ipfs-cluster queue and regularly fills it up to 25k elements. We are using the metric `ipfs_cluster.ipfscluster_pins_pin_queued` to watch the queue size.

Based on the monitoring, the queue is never bigger than 25k elements.

We started to get the following error:
```
error finalizing adder:error batching item: batching max_queue_size reached. Too many operations are waiting to be batched. Try increasing the max_queue_size or adjusting the batching options
```

But the IPFS cluster (with only 2 nodes) is configured to have a max queue size of 50k. We bumped it to 500k and the error vanished, until this morning, while the monitoring still shows a maximum of 25k elements (right now, we have 21k elements in the queue, but the error still shows up when we call `/pin` or `/add`).

Here is the script configuring our cluster (the rest of the values are the default ones, generated by `ipfs-cluster-service init`)
```
jq '.cluster.pin_recover_interval = "6h"
   | .cluster.state_sync_interval = "6h"
   | .consensus.crdt.rebroadcast_interval = "1m0s"
   | .consensus.crdt.batching.max_batch_size = 10000
   | .consensus.crdt.batching.max_batch_age = "30s"
   | .consensus.crdt.batching.max_queue_size = 500000
   | .ipfs_connector.ipfshttp.pin_timeout = "2m0s"
   | .ipfs_connector.ipfshttp.ipfs_request_timeout = "10m"
   | .pin_tracker.stateless.concurrent_pins = 30
   ' /ipfs-data/cluster/service.json >/ipfs-data/cluster/service.json.new
 ```

Any idea what is going on?

Happy to provide any additional information you may need :)

**Comment by Mayeu** [comment]
Something I forgot, right now we are only missing around ~250k CID to be pinned. So it's not even the size of the current 500k element queue.

**Comment by hsanjuan** [comment]
Hello,

`batching.max_queue_size` is the maximum number of elements that can be waiting to be committed into a batch. This is unrelated to "pin_queued" metrics, which tracks how many committed items are queued for pinning.

So the first problem is that your batching queue seems to grow way faster than the speed batches can be committed to the network. I find this a bit surprising, given the batch size is 10k and that it should not be taking much to commit a batch (~1 second? if you use `--loglevel crdt:info` there should be some logging showing every time a batch is committed). In any case, if you hit the 500k limit this would mean you have sent 500k to pin really fast or something else is going on.

I don't know if there's a second problem, with the pinning queue. I would expect that if you overwhelm the batch-committing part, then at least all those 10k items that come through in every batch would go onto the pinning queue, which would make it go past 25k items pretty quickly. So perhaps batches are not going through, or perhaps most of the things you are putting in the batches are already pinned and do not become queued to start with.

For a start, I'd be interested in knowing how quickly your batches are getting committed. And whether the error you see happens because you sent 500k items in one second or something or happens constantly.

Then you could use `ipfs-cluster-ctl status --local --filter queued` to list the queued items (do some grepping to have 1 line per item only). The total number should match what the metric says - at least roughly.

**Comment by Mayeu** [comment]
Thank you for your response. It seems that we didn't understand that the what the batch.max_queue_size was in relation to that metric.

> In any case, if you hit the 500k limit this would mean you have sent 500k to pin really fast

This would be pretty surprising, we don't have that much new pins/unpins per second.  

I restarted our cluster yesterday with a smaller `batching.max_batch_age` (5s) to see if that helps.

Already something surprising, there are a few log entries about batch being committed around the time `ipfs-cluster-service` has been restarted, but since then no commit happened while there are logs entries showing that pin & unpin have been requested.

This node was restarted around 17:30 UTC:
```

Dec 19 17:32:53 ipfs-01 ipfs-cluster-service[1937488]: 2023-12-19T17:32:53.604Z        INFO        crdt        crdt/consensus.go:579        batch commit (max age): 3 items
Dec 19 17:33:10 ipfs-01 ipfs-cluster-service[1937488]: 2023-12-19T17:33:10.618Z        INFO        crdt        crdt/consensus.go:579        batch commit (max age): 2 items
Dec 19 17:33:16 ipfs-01 ipfs-cluster-service[1937488]: 2023-12-19T17:33:16.292Z        INFO        crdt        crdt/consensus.go:579        batch commit (max age): 1 items
Dec 19 17:33:33 ipfs-01 ipfs-cluster-service[1937488]: 2023-12-19T17:33:33.908Z        INFO        crdt        crdt/consensus.go:579        batch commit (max age): 2 items
Dec 19 17:34:13 ipfs-01 ipfs-cluster-service[1937488]: 2023-12-19T17:34:13.542Z        INFO        crdt        crdt/consensus.go:579        batch commit (max age): 2 items
```

And since 17:34 UTC, there are no new commit to the CRDT, but there is definitely new pin & unpin sent to the cluster.

(As you see from that, we haven't much new pin/unpin coming per second.)

Is there a way to check the current batching content or queue size ? It doesn't seem to have any metrics exported for that.

Additional observation, all those "batch commit" happened before the pintracker restarted ~34.5k  pin operation.

```
$ journalctl -u ipfs-cluster --since "2023-12-19 17:00:00" -g "Restarting pin operation" | wc -l
34489
```

(The other nodes returned 30k lines of logs for this.)

So for some reason when we restart the node we successfully batch new commit, but as soon as the pin restart happens we seem to stop having new commits. 

>  So perhaps batches are not going through, or perhaps most of the things you are putting in the batches are already pinned and do not become queued to start with.

We discovered that in the remaining CIDs to pin a big chunk was not available in the network (we are starting to unpin them currently). But since those have already been attempted, they must have already been committed to the CRDT so that should have no impact on the batching, right?

> Then you could use `ipfs-cluster-ctl status --local --filter queued` to list the queued items (do some grepping to have 1 line per item only). The total number should match what the metric says - at least roughly.

Yes, this match the exported metrics:
```
ipfs-cluster-ctl status --local --filter queued | grep ":$" | wc -l && ipfs-cluster-ctl health metrics pinqueue
21365
12D3xxxxxxxxxxxxxx | pinqueue: 21365 | Expires in: 26 seconds from now
12D3yyyyyyyyyyyyyy | pinqueue: 21251 | Expires in: 21 seconds from now
```

**Comment by hsanjuan** [comment]
> Already something surprising, there are a few log entries about batch being committed around the time ipfs-cluster-service has been restarted, but since then no commit happened while there are logs entries showing that pin & unpin have been requested.

If no elements are added/removed from the cluster, then there is nothing to batch, and no batches are committed. Meanwhile, the pin tracker component will be retrying items that should be pinned and are not. Another thing that happens async is the syncing of the crdt-dag, so even if you are not sending anything, if portions of the crdt-dag are being synced from other nodes, you will see that pins are being added as the crdt-nodes get processed.

> Is there a way to check the current batching content or queue size ? It doesn't seem to have any metrics exported for that.

No, but your batches are very small anyways.

> So for some reason when we restart the node we successfully batch new commit, but as soon as the pin restart happens we seem to stop having new commits. 

That's weird as the "batch-committing" workflow is fully independent from the "pin-tracking" part. Unless your storage has become a huge bottleneck or is completely hammered, but even so. Just to be clear, you say that you are doing /pin/add or /add calls and don't see batches happening even though you sucessfully perform those calls and obtain a 200 result?

Perhaps it helps to pull out the stack dump (`curl localhost:8888/debug/pprof/goroutine\?debug=2 > cluster.stacks`). That should show where the goroutines are.

**Comment by Mayeu** [comment]
Hello,

Sorry for the delay, with the holiday I did not work much on this issue.

> That's weird as the "batch-committing" workflow is fully independent from the "pin-tracking" part. 

Yeah, I jumped to this conclusion too quickly, I did see batches being committed after the initial pin tracking part. But it seems to stop after some time (see laters).

As you saw there were a lot of things, we assume but that are not working like we thought.

Right now, we have stopped requesting pins or unpins with data not produced by our users to the cluster. We only add data directly to it (via the `/add` endpoint), and we have a job requesting to pin the added CIDs again since at some point we thought that would help (it did not). We are focussed on making the `/add` work again before pining the rest of the data.

I have taken a stack dump: [cluster.stacks.zip](https://github.com/ipfs-cluster/ipfs-cluster/files/13863044/cluster.stacks.zip).

Right now we are observing the following:
- The size of the pinset didn't change at all since the 28th of December, but we are adding a handful of files to the cluster every minute
  - I'm getting this by using the logs (`journalctl -u ipfs-cluster -g "Full pinset listing finished"`), it shows the same number since the 28th of December. Most likely since way before, we just don't have the logs anymore.
  - The cluster pinset is around 14 millions, and now have around 3 millions new CIDs to add there tracked by our database.  
- Using the `/add` endpoint on the cluster seems to be leaving the data unpinned. I checked some CID added recently and they aren't pin. Which is consistent with the fact that the pinset didn't grow at all.
- There was no CRDT merge since the 28th of December, nor any logs talking about batching.
- We thought that maybe there was too much unreachable data, so we configured the nodes to remove the pins newer than 2h and with more than 1 retry from the priority queue. We hoped that this would have allowed us to process the `/add` as we got them, but this doesn't seem to have changed anything.
- No errors are returned on `/pin` & `/add` by the cluster, and from the logs everything looks OK.

It feels like something is stuck, and we are not sure how to move forward.

We are thinking of starting a fresh new cluster on one of our nodes, but to keep all the data stored by Kubo to not have to download everything again. We would only use `/add` at first until this part is stable, and then repin everything else slowly.

**Comment by hsanjuan** [comment]
Notes when I look at the stack:

1. crdt: Dag workers are waiting for jobs since very long ago. Send worker is waiting (no jobs to send).
2. Some pebble routines waiting too for very long
3. Some bitswap routines also waiting for very long
4. sendToBatchWorker does not seem to have been waiting for long
5. goroutine 728 [sync.Mutex.Lock, 17127 minutes]:
  * We are waiting to commit a batch to the datastore. Pebble is locked.
  * Thus, batch worker is deadlocked and always busy...

Ok, so the problem is in cockroachdb. It's not taking any writes, so everything you send is queued up for batching/broadcasting but nothing really committed.

Just to confirm, you are running with default pebble settings right? I would like you to run the daemon with `ipfs-cluster-service --loglevel pebble:debug daemon`. This will printout pebble debug stats every minute and I would like to see a few those. I suspect pebble is compacting or something and stopped taking writes. Do you have disk stats? It might help to move the .ipfs_cluster folder onto an ssd if not on one already.

**Comment by Mayeu** [comment]
Thank you for checking that out.

Our cluster runs on a ZFS pool (6 drives) that uses an NVMe drive as read & write cache.

We do have statistics (we run Netdata on the cluster nodes). Are there specific metrics you are interested in?

I have activated the debug log and let it run on our ZFS setup. And now I have moved the cluster data to only the NVMe drive using ext4. I'll let it run a bit and will send you the pebble stats for both configurations.

**Comment by Mayeu** [comment]
Sidenote: while restarting the ipfs-cluster I noted that the `pebble/LOCK` file is not deleted, is that file needed to be absent on start?

**Comment by Mayeu** [comment]
Here are the pebble stats:
- [pebble-stats-zfs-pool.log.zip](https://github.com/ipfs-cluster/ipfs-cluster/files/13874431/pebble-stats-zfs-pool.log.zip)
- [pebble-stats-ssd.log.zip](https://github.com/ipfs-cluster/ipfs-cluster/files/13874432/pebble-stats-ssd.log.zip)

**Comment by Mayeu** [comment]
After a few hours, I don't see any batch commit anymore in the logs, and the stack dump shows that the `sync.Mutex.Lock` has been waiting for more than 2h now.

So it seems that pebble deadlocked again?

[2024-01-09-ipfs-cluster.stacks.zip](https://github.com/ipfs-cluster/ipfs-cluster/files/13876024/2024-01-09-ipfs-cluster.stacks.zip)

I'm also noticing now that when we shutdown the cluster the default systemd timeout waiting for the process to stopped is reached. I tried to bump it to 10 minutes but that was not enough. I'll try with an hour to see if it change anything.

**Comment by hsanjuan** [comment]
> Sidenote: while restarting the ipfs-cluster I noted that the `pebble/LOCK` file is not deleted, is that file needed to be absent on start?

Probably not the issue, but please try deleting.

I believe the issue is a bug in Pebble causing a deadlock when rotating memtables. I wonder if you can compile and run with this update: https://github.com/ipfs-cluster/ipfs-cluster/pull/2018

Chances are this has been fixed upstream. v1.0.7 runs with a version from February 2023 so I'm crossing my fingers.

Your database stats actually look ok. There's not much data in total, perfectly manageable... except level1 seems due for compacting but it is probably stuck.

**Comment by hsanjuan** [comment]
@Mayeu re: #2018 , please backup your `.ipfs-cluster` folder, then you need to edit the pebble configuration in `service.json` to set `" format_major_version": 13`, otherwise it will refuse to start.

**Comment by Mayeu** [comment]
> > Sidenote: while restarting the ipfs-cluster I noted that the `pebble/LOCK` file is not deleted, is that file needed to be absent on start?
> 
> Probably not the issue, but please try deleting.

It doesn't seems to change anything. Present or not the behaviour seems similar.

**Comment by hsanjuan** [comment]
I have been testing a bit. For me updating FormatMajorVersion doesn't change anything. I have added some 100k CIDs and changed the config to have really small tables but that doesn't seem to get me to a place where I could not change back and forth between version 1 and version 14.. and updating pebble into version 16.

So I have added #2019 so that at least new installations get the highest available format version. And I added a warning whenver the highest does not correspond to the one in the configuration so that users can bump the version in their configuration.

I bit worrying is that I did experience a Pebble deadlock on shutdown... but my config was really messed at that point, and it didn't deadlock again when I restored the default config. In the worst case we will move up to to latest pebble master again.
